import type { VerticalConfig } from "@retailos/shared";

export const pharmacyConfig: VerticalConfig = {
  vertical: "PHARMACY",
  displayName: "Pharmacy / Medical shop",
  icon: "pill",
  modules: {
    billing: true,
    inventory: true,
    delivery: true,
    payments: true,
    purchaseOrders: true,
    suppliers: true,
    reports: true,
    customers: true,
  },
  productFields: [
    { key: "name", label: "Medicine name", type: "text", required: true },
    { key: "sku", label: "SKU / Item code", type: "text", required: false },
    { key: "barcode", label: "Barcode", type: "text", required: false },
    {
      key: "unit",
      label: "Unit",
      type: "select",
      required: true,
      options: ["strip", "bottle", "tablet", "injection", "tube", "sachet"],
    },
    { key: "mrp", label: "MRP (₹)", type: "decimal", required: true },
    { key: "sellingPrice", label: "Selling price (₹)", type: "decimal", required: true },
    { key: "purchasePrice", label: "Purchase price (₹)", type: "decimal", required: false },
    { key: "gstRate", label: "GST %", type: "select", required: true, options: ["0", "5", "12", "18"] },
    { key: "hsnCode", label: "HSN code", type: "text", required: false },
    { key: "reorderLevel", label: "Reorder level", type: "decimal", required: false },
    { key: "verticalData.manufacturer", label: "Manufacturer", type: "text", required: false, vertical: true },
    {
      key: "verticalData.drugSchedule",
      label: "Drug schedule",
      type: "select",
      required: false,
      vertical: true,
      options: ["None", "H", "H1", "X", "G", "J"],
    },
    {
      key: "verticalData.prescriptionRequired",
      label: "Prescription required",
      type: "boolean",
      required: false,
      vertical: true,
    },
  ],
  batchFields: [
    { key: "batchNumber", label: "Batch number", type: "text", required: true },
    { key: "expiryDate", label: "Expiry date", type: "date", required: true },
    { key: "quantity", label: "Quantity", type: "decimal", required: true },
    { key: "purchasePrice", label: "Purchase price", type: "decimal", required: true },
  ],
  billingFields: [
    { key: "verticalData.prescriptionNumber", label: "Prescription no.", type: "text", required: false, vertical: true },
  ],
  expiryAlerts: {
    enabled: true,
    thresholds: [30, 60, 90],
  },
  billTemplate: "pharmacy-gst-bill",
  reportTemplates: ["daily-sales", "expiry-report", "stock-report", "purchase-report"],
  navigation: [
    { label: "Billing", icon: "receipt", href: "/billing" },
    { label: "Inventory", icon: "boxes", href: "/inventory" },
    { label: "Expiry", icon: "alert", href: "/inventory/expiry" },
    { label: "Delivery", icon: "truck", href: "/delivery" },
    { label: "Payments", icon: "wallet", href: "/payments" },
    { label: "Customers", icon: "users", href: "/customers" },
    { label: "Suppliers", icon: "building", href: "/suppliers" },
    { label: "Purchases", icon: "shopping-bag", href: "/purchases" },
    { label: "Reports", icon: "chart", href: "/reports" },
    { label: "Settings", icon: "settings", href: "/settings" },
  ],
};
