#!/usr/bin/env bash
set -Eeuo pipefail

DEPLOY_BRANCH="${DEPLOY_BRANCH:-develop}"
DEPLOY_SHA="${DEPLOY_SHA:-}"
COMPOSE_FILE="${COMPOSE_FILE:-infra/docker-compose.test.yml}"
ENV_FILE="${ENV_FILE:-.env.testing}"

cd "$(dirname "$0")/.."
# shellcheck source=lib/deploy-compat.sh
source "$(dirname "$0")/lib/deploy-compat.sh"

if [[ -z "$DEPLOY_SHA" ]]; then
  echo "DEPLOY_SHA is required for testing deployments." >&2
  exit 1
fi

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

if [[ ! -f "$ENV_FILE" ]]; then
  echo "==> Missing $ENV_FILE; creating a testing-only environment file"
  cp .env.testing.example "$ENV_FILE"
  TEST_POSTGRES_PASSWORD="$(random_secret)"
  TEST_REDIS_PASSWORD="$(random_secret)"
  TEST_MINIO_PASSWORD="$(random_secret)"
  TEST_JWT_SECRET="$(random_secret)$(random_secret)"
  TEST_WHATSAPP_TOKEN_KEY="$(random_secret)"
  {
    echo ""
    echo "# Generated by infra/deploy-testing.sh on first deployment."
    echo "NEXT_PUBLIC_APP_URL=https://test.bizbil.com"
    echo "NEXT_PUBLIC_APP_NAME=BizBil Testing"
    echo "TEST_APP_DOMAIN=test.bizbil.com"
    echo "POSTGRES_PASSWORD=$TEST_POSTGRES_PASSWORD"
    echo "DATABASE_URL=postgresql://bizbil:$TEST_POSTGRES_PASSWORD@postgres:5432/bizbil_test"
    echo "REDIS_PASSWORD=$TEST_REDIS_PASSWORD"
    echo "REDIS_URL=redis://:$TEST_REDIS_PASSWORD@redis:6379"
    echo "MINIO_ROOT_PASSWORD=$TEST_MINIO_PASSWORD"
    echo "JWT_SECRET=$TEST_JWT_SECRET"
    echo "WHATSAPP_TOKEN_ENCRYPTION_KEY=$TEST_WHATSAPP_TOKEN_KEY"
  } >> "$ENV_FILE"
fi

get_env_value() {
  local key="$1"
  local line

  line="$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 || true)"
  if [[ -z "$line" ]]; then
    return 1
  fi

  line="${line#*=}"
  line="${line%$'\r'}"
  printf '%s' "$line"
}

append_env_value() {
  local key="$1"
  local value="$2"

  {
    echo ""
    echo "# Managed override: added by testing deploy compatibility checks."
    echo "${key}=${value}"
  } >> "$ENV_FILE"
}

ensure_compose_project_volumes "bizbil-test" "$(legacy_compose_project_name "-test")"

port_is_listening() {
  local port="$1"

  bash -c ":</dev/tcp/127.0.0.1/${port}" >/dev/null 2>&1
}

find_free_test_port() {
  local preferred_port="$1"
  local port

  for ((port = preferred_port; port <= preferred_port + 99; port++)); do
    if ! port_is_listening "$port"; then
      printf '%s' "$port"
      return 0
    fi
  done

  return 1
}

TEST_HTTP_PORT_VALUE="$(get_env_value TEST_HTTP_PORT || true)"
TEST_HTTP_PORT_PREFERRED="${TEST_HTTP_PORT_VALUE:-3100}"
if [[ "$TEST_HTTP_PORT_PREFERRED" == "80" ]]; then
  TEST_HTTP_PORT_PREFERRED=3100
fi

TEST_HTTP_PORT_CHOSEN="$(find_free_test_port "$TEST_HTTP_PORT_PREFERRED" || true)"
if [[ -z "$TEST_HTTP_PORT_CHOSEN" ]]; then
  echo "Could not find a free test HTTP port starting from ${TEST_HTTP_PORT_PREFERRED}." >&2
  exit 1
fi

if [[ -z "$TEST_HTTP_PORT_VALUE" || "$TEST_HTTP_PORT_VALUE" == "80" || "$TEST_HTTP_PORT_VALUE" != "$TEST_HTTP_PORT_CHOSEN" ]]; then
  echo "==> Setting test stack internal proxy port to ${TEST_HTTP_PORT_CHOSEN}"
  {
    echo ""
    echo "# Managed override: host nginx owns public 80/443 and proxies to this local port."
    echo "TEST_HTTP_PORT=${TEST_HTTP_PORT_CHOSEN}"
  } >> "$ENV_FILE"
fi

configure_host_nginx() {
  local domain
  local port
  local config_path
  local cert_path
  local key_path

  domain="$(get_env_value TEST_APP_DOMAIN || true)"
  port="$(get_env_value TEST_HTTP_PORT || true)"

  domain="${domain:-test.bizbil.com}"
  port="${port:-${TEST_HTTP_PORT_CHOSEN:-3100}}"
  cert_path="/etc/letsencrypt/live/${domain}/fullchain.pem"
  key_path="/etc/letsencrypt/live/${domain}/privkey.pem"

  if [[ "$(id -u)" != "0" ]]; then
    echo "==> Skipping host nginx configuration because deploy user is not root"
    return
  fi

  if ! command -v nginx >/dev/null 2>&1; then
    echo "==> Skipping host nginx configuration because nginx is not installed"
    return
  fi

  config_path="/etc/nginx/sites-available/${domain}"
  echo "==> Configuring host nginx proxy for ${domain} -> 127.0.0.1:${port}"
  if [[ -f "$cert_path" && -f "$key_path" ]]; then
    cat > "$config_path" <<NGINX
server {
  listen 80;
  listen [::]:80;
  server_name ${domain};
  return 301 https://\$host\$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name ${domain};

  ssl_certificate ${cert_path};
  ssl_certificate_key ${key_path};

  client_max_body_size 25m;

  location / {
    proxy_pass http://127.0.0.1:${port};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
NGINX
  else
    cat > "$config_path" <<NGINX
server {
  listen 80;
  listen [::]:80;
  server_name ${domain};

  client_max_body_size 25m;

  location / {
    proxy_pass http://127.0.0.1:${port};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
NGINX
  fi

  ln -sf "$config_path" "/etc/nginx/sites-enabled/${domain}"
  nginx -t
  systemctl reload nginx

  if command -v certbot >/dev/null 2>&1 && [[ ! -f "$cert_path" ]]; then
    echo "==> Requesting Let's Encrypt certificate for ${domain}"
    certbot --nginx -d "$domain" --non-interactive --agree-tos -m "admin@bizbil.com" --redirect
  elif command -v certbot >/dev/null 2>&1; then
    echo "==> Existing Let's Encrypt certificate found for ${domain}"
  fi
}

POSTGRES_TARGET_USER="$(get_env_value POSTGRES_USER || true)"
POSTGRES_TARGET_PASSWORD="$(get_env_value POSTGRES_PASSWORD || true)"
POSTGRES_TARGET_DB="$(get_env_value POSTGRES_DB || true)"
POSTGRES_LEGACY_USER="$(get_env_value POSTGRES_LEGACY_USER || true)"
POSTGRES_LEGACY_DB="$(get_env_value POSTGRES_LEGACY_DB || true)"

if [[ -z "$POSTGRES_TARGET_USER" ]]; then
  POSTGRES_TARGET_USER="bizbil"
fi

if [[ -z "$POSTGRES_TARGET_DB" ]]; then
  POSTGRES_TARGET_DB="bizbil_test"
fi

if [[ -z "$POSTGRES_LEGACY_DB" ]]; then
  POSTGRES_LEGACY_DB="$(legacy_database_name "_test")"
fi

if [[ -z "$POSTGRES_TARGET_PASSWORD" ]]; then
  echo "POSTGRES_PASSWORD is required in $ENV_FILE" >&2
  exit 1
fi

if [[ -n "${GH_PAT:-}" && -n "${GITHUB_REPOSITORY:-}" ]]; then
  echo "==> Ensuring origin points to GitHub"
  git remote set-url origin "https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git"
fi

echo "==> Fetching exact ${DEPLOY_BRANCH} commit"
echo "Deploying commit: $DEPLOY_SHA"
git fetch origin
git checkout -B "$DEPLOY_BRANCH" "$DEPLOY_SHA"
git reset --hard "$DEPLOY_SHA"
echo "Now at: $(git rev-parse HEAD) - $(git log -1 --format='%s')"

DEPLOY_TIME="${DEPLOY_TIME:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}"
export DEPLOY_SHA DEPLOY_BRANCH DEPLOY_TIME

echo "==> Building testing application images"
build_log="$(mktemp)"
if ! docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" build api web >"$build_log" 2>&1; then
  cat "$build_log"
  rm -f "$build_log"
  exit 1
fi
tail -n 40 "$build_log"
rm -f "$build_log"

echo "==> Starting testing dependencies"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d postgres minio
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --force-recreate redis

POSTGRES_CONTAINER="$(docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps -q postgres)"
if [[ -z "$POSTGRES_CONTAINER" ]]; then
  echo "Could not determine the testing postgres container." >&2
  exit 1
fi

echo "==> Waiting for testing postgres readiness"
postgres_ready=false
for attempt in {1..30}; do
  if docker exec -u postgres "$POSTGRES_CONTAINER" pg_isready -d postgres >/dev/null 2>&1; then
    postgres_ready=true
    break
  fi
  sleep 2
done

if [[ "$postgres_ready" != "true" ]]; then
  echo "Testing postgres did not become ready." >&2
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps -a
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail=120 postgres
  exit 1
fi

find_postgres_admin_user() {
  local candidate
  local candidates=()
  local legacy_user

  candidates+=("$POSTGRES_TARGET_USER")
  if [[ -n "$POSTGRES_LEGACY_USER" ]]; then
    candidates+=("$POSTGRES_LEGACY_USER")
  fi
  legacy_user="$(legacy_database_user)"
  candidates+=("$legacy_user" "postgres")

  for candidate in "${candidates[@]}"; do
    if docker exec -u postgres "$POSTGRES_CONTAINER" \
      psql -v ON_ERROR_STOP=1 -U "$candidate" -d postgres -tAc "SELECT 1" >/dev/null 2>&1; then
      printf '%s' "$candidate"
      return 0
    fi
  done

  return 1
}

POSTGRES_ADMIN_USER="$(find_postgres_admin_user || true)"
if [[ -z "$POSTGRES_ADMIN_USER" ]]; then
  echo "Could not find a Postgres admin role. Tried ${POSTGRES_TARGET_USER}, ${POSTGRES_LEGACY_USER:-<empty>}, legacy app role, and postgres." >&2
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail=120 postgres
  exit 1
fi

reconcile_postgres_database_name \
  "$POSTGRES_CONTAINER" \
  "$POSTGRES_ADMIN_USER" \
  "$POSTGRES_TARGET_DB" \
  "$POSTGRES_LEGACY_DB"

echo "==> Reconciling testing database credentials from $ENV_FILE"
docker exec -i -u postgres "$POSTGRES_CONTAINER" \
  psql -v ON_ERROR_STOP=1 -U "$POSTGRES_ADMIN_USER" -d postgres \
    -v target_user="${POSTGRES_TARGET_USER}" \
    -v target_password="${POSTGRES_TARGET_PASSWORD}" \
    -v target_database="${POSTGRES_TARGET_DB}" <<'SQL'
SELECT format('CREATE ROLE %I WITH LOGIN PASSWORD %L', :'target_user', :'target_password')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'target_user')\gexec

ALTER ROLE :"target_user" WITH LOGIN PASSWORD :'target_password';

SELECT format('CREATE DATABASE %I OWNER %I', :'target_database', :'target_user')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'target_database')\gexec

ALTER DATABASE :"target_database" OWNER TO :"target_user";
SQL

echo "==> Running testing database migrations"
if [[ "${RESET_DATABASE:-false}" == "true" ]]; then
  echo "==> WARNING: database reset requested for testing deployment"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" run --rm api \
    pnpm --filter @bizbil/api exec -- prisma migrate reset --force --skip-seed --schema prisma/schema.prisma
else
  if ! docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" run --rm api \
    pnpm --filter @bizbil/api exec -- prisma migrate deploy --schema prisma/schema.prisma; then
    echo "==> Prisma migrate deploy failed for the testing database" >&2
    exit 1
  fi
fi

echo "==> Restarting testing application services"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" up -d --force-recreate --remove-orphans api web caddy

configure_host_nginx

echo "==> Waiting for testing API readiness"
api_ready=false
for attempt in {1..30}; do
  if docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps --status running --services api | grep -qx api; then
    if docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T api node -e "fetch('http://127.0.0.1:' + (process.env.PORT || '3001') + '/health').then(async (response) => { if (!response.ok) { console.error(await response.text()); process.exit(1); } }).catch((error) => { console.error(error); process.exit(1); })"; then
      api_ready=true
      break
    fi
  fi
  sleep 2
done

if [[ "$api_ready" != "true" ]]; then
  echo "Testing API did not become ready; dumping focused API diagnostics" >&2
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps -a
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail=200 api
  exit 1
fi

echo "==> Waiting for testing proxy to reach API"
proxy_ready=false
for attempt in {1..30}; do
  if docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T caddy wget -qO- http://api:3001/health; then
    proxy_ready=true
    break
  fi
  sleep 2
done

if [[ "$proxy_ready" != "true" ]]; then
  echo "Testing proxy could not reach API; dumping focused network diagnostics" >&2
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps -a
  echo "--- container networks ---"
  docker inspect \
    "$(docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps -q api)" \
    "$(docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps -q caddy)" \
    --format '{{.Name}} {{json .NetworkSettings.Networks}}'
  echo "--- caddy resolver ---"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T caddy cat /etc/resolv.conf || true
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" exec -T caddy nslookup api || true
  echo "--- api logs ---"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail=120 api
  echo "--- caddy logs ---"
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" logs --tail=80 caddy
  exit 1
fi

echo "==> Testing service status"
docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" ps api web caddy postgres redis minio
