import type { LabelCanvasDefinition, LabelLayoutMode, LabelTemplateRecord } from "./labels.types.js";

function starterCanvas(title: string, widthMm: number, heightMm: number, layoutMode: LabelLayoutMode): LabelCanvasDefinition {
  const qrX = layoutMode === "2up" ? widthMm - 18 : widthMm - 24;
  return {
    fields: [
      {
        id: "store-name",
        type: "static_text",
        x: 4,
        y: 3,
        width: widthMm - 8,
        height: 6,
        rotation: 0,
        fontSize: 11,
        fontWeight: "bold",
        textContent: title,
      },
      {
        id: "product-name",
        type: "product_name",
        x: 4,
        y: 11,
        width: widthMm - 30,
        height: 8,
        rotation: 0,
        fontSize: 13,
        fontWeight: "bold",
      },
      {
        id: "price",
        type: "price",
        x: 4,
        y: 20,
        width: widthMm - 28,
        height: 8,
        rotation: 0,
        fontSize: 14,
        fontWeight: "bold",
      },
      {
        id: "quantity",
        type: "quantity",
        x: 4,
        y: 29,
        width: 18,
        height: 7,
        rotation: 0,
        fontSize: 9,
      },
      {
        id: "packed-date",
        type: "packed_date",
        x: 4,
        y: 37,
        width: widthMm / 2 - 6,
        height: 6,
        rotation: 0,
        fontSize: 8,
      },
      {
        id: "best-before",
        type: "best_before",
        x: 4,
        y: 44,
        width: widthMm / 2 - 6,
        height: 6,
        rotation: 0,
        fontSize: 8,
      },
      {
        id: "barcode",
        type: "barcode",
        x: 4,
        y: 49,
        width: widthMm - 28,
        height: 9,
        rotation: 0,
        codeType: "barcode",
      },
      {
        id: "qr-code",
        type: "qr_code",
        x: qrX,
        y: 28,
        width: 20,
        height: 20,
        rotation: 0,
        codeType: "qr",
      },
    ],
  };
}

export const DEFAULT_LABEL_TEMPLATES: readonly LabelTemplateRecord[] = [
  {
    id: "default-wheat-flour-108x60",
    name: "Wheat Flour 108 × 60",
    width_mm: 108,
    height_mm: 60,
    layout_mode: "1up",
    canvas_json: starterCanvas("Wheat Flour", 108, 60, "1up"),
    is_default: true,
    created_at: new Date(0).toISOString(),
    updated_at: new Date(0).toISOString(),
    deleted_at: null,
    created_by: null,
  },
  {
    id: "default-wheat-flour-52x60",
    name: "Wheat Flour 2-up 52 × 60",
    width_mm: 52,
    height_mm: 60,
    layout_mode: "2up",
    canvas_json: starterCanvas("Wheat Flour", 52, 60, "2up"),
    is_default: true,
    created_at: new Date(0).toISOString(),
    updated_at: new Date(0).toISOString(),
    deleted_at: null,
    created_by: null,
  },
  {
    id: "default-minimal-80x40",
    name: "Minimal Shelf Sticker 80 × 40",
    width_mm: 80,
    height_mm: 40,
    layout_mode: "1up",
    canvas_json: {
      fields: [
        {
          id: "product-name",
          type: "product_name",
          x: 4,
          y: 4,
          width: 72,
          height: 8,
          rotation: 0,
          fontSize: 11,
          fontWeight: "bold",
        },
        {
          id: "price",
          type: "price",
          x: 4,
          y: 14,
          width: 40,
          height: 8,
          rotation: 0,
          fontSize: 13,
          fontWeight: "bold",
        },
        {
          id: "static-text",
          type: "static_text",
          x: 4,
          y: 24,
          width: 60,
          height: 6,
          rotation: 0,
          fontSize: 8,
          textContent: "BizBil label sample",
        },
        {
          id: "qr-code",
          type: "qr_code",
          x: 62,
          y: 10,
          width: 14,
          height: 14,
          rotation: 0,
          codeType: "qr",
        },
      ],
    },
    is_default: true,
    created_at: new Date(0).toISOString(),
    updated_at: new Date(0).toISOString(),
    deleted_at: null,
    created_by: null,
  },
];
