INSERT INTO "invoice_templates" (
  "id",
  "tenant_id",
  "name",
  "description",
  "paper_size",
  "render_type",
  "html_source",
  "escpos_config",
  "ui_config",
  "is_system",
  "is_default",
  "is_locked",
  "cloned_from_id",
  "version",
  "created_at",
  "updated_at"
) VALUES (
  'system-sivsan-detailed-thermal-3',
  NULL,
  'Sivsan Oils 3 inch Detailed Thermal Receipt',
  'Detailed 3 inch ESC/POS receipt matching the Sivsan Oils counter bill layout.',
  'THERMAL_3',
  'ESC_POS',
  NULL,
  '{
    "layout": "SIVSAN_DETAILED_3IN",
    "columns": 42,
    "cut": true,
    "feedLinesBeforeCut": 6,
    "showShopName": true,
    "showAddress": true,
    "showPhone": true,
    "showGstin": false,
    "showCustomer": true,
    "showSubtotal": true,
    "showDiscount": true,
    "showDiscountOnlyWhenPresent": false,
    "showCgst": false,
    "showSgst": false,
    "showPaid": false,
    "showDue": false,
    "showDueOnlyWhenPresent": true,
    "showBatch": false,
    "alternatePhone": "7013303876",
    "fssaiNumber": "13620010000289",
    "logoText": "",
    "note": "Transfer the OILS to Steel or Glass vessels for Maximum Freshness",
    "currencyLabel": "Rs",
    "footerMessage": "Thank You... Visit Again !",
    "labels": {
      "invoice": "Inv No",
      "date": "Date",
      "customer": "Name",
      "itemHeader": "Item",
      "amountHeader": "Amount",
      "subtotal": "Subtotal",
      "discount": "DISC. AMOUNT",
      "cgst": "CGST",
      "sgst": "SGST",
      "total": "GRAND TOTAL",
      "paid": "Paid",
      "due": "Due"
    }
  }'::jsonb,
  '{"header": {"style": "sivsan-detailed", "showAddress": true, "showPhone": true, "showFssai": true}, "items": {"layout": "sr-name-qty-price-amount"}, "footer": {"message": "Thank You... Visit Again !"}}'::jsonb,
  true,
  false,
  true,
  NULL,
  1,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("id") DO UPDATE
SET
  "name" = EXCLUDED."name",
  "description" = EXCLUDED."description",
  "paper_size" = EXCLUDED."paper_size",
  "render_type" = EXCLUDED."render_type",
  "escpos_config" = EXCLUDED."escpos_config",
  "ui_config" = EXCLUDED."ui_config",
  "is_system" = true,
  "is_default" = false,
  "is_locked" = true,
  "updated_at" = CURRENT_TIMESTAMP;
