import {
  Activity,
  AlertTriangle,
  BarChart3,
  Boxes,
  Building2,
  CreditCard,
  FileText,
  FileMinus,
  FolderOpen,
  Hammer,
  Home,
  LayoutDashboard,
  MessageCircle,
  PackageX,
  Pill,
  Receipt,
  Settings,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Star,
  Tag,
  TrendingDown,
  Truck,
  Users,
  Utensils,
  Wallet,
} from "lucide-react";

export const iconMap = {
  activity: Activity,
  alert: AlertTriangle,
  boxes: Boxes,
  building: Building2,
  categories: FolderOpen,
  chart: BarChart3,
  "credit-note": FileMinus,
  dashboard: LayoutDashboard,
  expenses: TrendingDown,
  "file-text": FileText,
  hammer: Hammer,
  home: Home,
  loyalty: Star,
  "message-circle": MessageCircle,
  pill: Pill,
  "purchase-return": PackageX,
  receipt: Receipt,
  restaurant: Utensils,
  settings: Settings,
  shield: Shield,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  smartphone: Smartphone,
  tag: Tag,
  truck: Truck,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  card: CreditCard,
};
