import {
  AlertTriangle,
  BarChart3,
  Boxes,
  Building2,
  CreditCard,
  Hammer,
  Pill,
  Receipt,
  Settings,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Truck,
  Users,
  Utensils,
  Wallet,
} from "lucide-react";

export const iconMap = {
  alert: AlertTriangle,
  boxes: Boxes,
  building: Building2,
  chart: BarChart3,
  hammer: Hammer,
  pill: Pill,
  receipt: Receipt,
  settings: Settings,
  shield: Shield,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-basket": ShoppingBasket,
  smartphone: Smartphone,
  truck: Truck,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  card: CreditCard,
};
